name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1


      - run: echo FN=_$RANDOM_ >> $GITHUB_ENV      
      - run: echo 'y' | sfdx plugins:install sfdx-mohanc-plugins
      - run: sfdx plugins

      # slides generator
      - run: sfdx mohanc:slides:gen -i ./input.md -o ./${{env.FN}}.md.html -t 'Title for the slides'
      - run: echo ${{ secrets.SEL_AUTH_URL}} > ./mysecret.txt
      - run: sfdx auth:sfdxurl:store -f ./mysecret.txt -s -a targetOrg

      - run: sfdx mohanc:org:viz   -u ${{ secrets.SEL_UN }}

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # commit files
      - run: |
          git add  ./${{env.FN}}.md.html Org.svg
          git commit -m "updated slides html file"
          git push origin main

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
      - run: node --version
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
